FROM ubuntu:22.04 
RUN apt update && apt install python3-pip -y
RUN /mnt/remote/whisper/Ascend-cann-toolkit_7.0.1.1_linux-aarch64.run --quiet --full 
RUN /mnt/remote/whisper/Ascend-cann-kernels-910b_7.0.1.1_linux.run --quiet --install
COPY ./bin/miniconda-installer.sh /mnt/remote/whisper/.
RUN chmod +x /mnt/remote/whisper/*
RUN /mnt/remote/whisper/miniconda-installer.sh -b -p /root/miniconda3/
RUN /usr/local/Ascend/ascend-toolkit/set_env.sh
RUN export LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64/driver/:$LD_LIBRARY_PATH
RUN /root/miniconda3/bin/activate

#RUN pip install torch==2.1.0 -i https://mirrors.aliyun.com/pypi/simple/
RUN pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 -i https://mirrors.aliyun.com/pypi/simple/
RUN pip install /mnt/remote/whisper/torch_npu-2.1.0.post2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
RUN pip install decorator attrs psutil absl-py cloudpickle scipy synr==0.5.0 tornado numpy pandas sentencepiece accelerate transformers==4.37.0 datasets -i https://mirrors.aliyun.com/pypi/simple/

